/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */
export const CHANGE_FORM = 'CHANGE_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const GET_PROFILE = 'GET_PROFILE';
export const PATCH_PROFILE = 'PATCH_PROFILE';
export const ERROR_PROFILE = 'ERROR_PROFILE';
export const ERROR_PROP = 'ERROR_PROP';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';
export const AUTH_USER_FROM_LOCALSTORE = 'AUTH_USER_FROM_LOCALSTORE';
export const UNAUTH_USER = 'UNAUTH_USER';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_FAIL = 'GET_USER_GROUPS_FAIL';

export const GET_AVAILABLE_USER_GROUPS_SUCCESS = 'GET_AVAILABLE_USER_GROUPS_SUCCESS';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

export const GET_STATUSES = 'GET_STATUSES';
export const GET_STATUSES_SUCCESS = 'GET_STATUSES_SUCCESS';
export const GET_STATUSES_FAIL = 'GET_STATUSES_FAIL';

export const GET_TRAFFICLIGHT = 'GET_TRAFFICLIGHT';
export const GET_TRAFFICLIGHT_SUCCESS = 'GET_TRAFFICLIGHT_SUCCESS';
export const GET_TRAFFICLIGHT_FAIL = 'GET_TRAFFICLIGHT_FAIL';

export const GET_TRAFFICLIGHTUNIT = 'GET_TRAFFICLIGHTUNIT';
export const GET_TRAFFICLIGHTUNIT_SUCCESS = 'GET_TRAFFICLIGHTUNIT_SUCCESS';
export const GET_TRAFFICLIGHTUNIT_FAIL = 'GET_TRAFFICLIGHTUNIT_FAIL';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
